
import json
from datetime import datetime, timedelta

import pytest

pytest.importorskip("flask")
pytest.importorskip("flask_sqlalchemy")

from app import create_app
from database import (
    Plan,
    PlanExecution,
    OperationalOutcome,
    SystemSnapshot,
    PlanEvaluation,
    db,
)
from agents.planner_agent import PlannerAgent


@pytest.fixture()
def app():
    app = create_app({
        "TESTING": True,
        "SQLALCHEMY_DATABASE_URI": "sqlite:///:memory:",
        "SOLARGRID_RAG_PREWARM": False,
        "SOLARGRID_AUTOMATION_ENABLED": False,
    })
    with app.app_context():
        yield app
        db.drop_all()


@pytest.fixture()
def recovery_case(app):
    with app.app_context():
        t0 = datetime.utcnow()
        original_snapshot = SystemSnapshot(
            timestamp=t0,
            demand_mw=62.0,
            solar_gen_mw=44.0,
            other_gen_mw=0.0,
            battery_soc_pct=60.0,
            reserve_margin_mw=20.0,
            grid_status="STABLE",
            state_json={"batteries": [{"current_power_mw": 0.0}]},
        )
        post_snapshot = SystemSnapshot(
            timestamp=t0 + timedelta(minutes=120),
            demand_mw=62.0,
            solar_gen_mw=40.0,
            other_gen_mw=0.0,
            battery_soc_pct=58.0,
            reserve_margin_mw=15.0,
            grid_status="STABLE",
            state_json={"batteries": [{"current_power_mw": 0.0}]},
        )
        db.session.add_all([original_snapshot, post_snapshot])
        db.session.flush()

        original = Plan(
            snapshot_id=original_snapshot.id,
            plan_name="Original recovery plan",
            horizon_hours=2,
            actions={},
            status="APPROVED",
            strategy_label="MIXED",
        )
        db.session.add(original)
        db.session.flush()

        execution = PlanExecution(
            plan_id=original.id,
            execution_timestamp=t0,
            requested_actions={"dispatch": "original"},
            actual_actions={"dispatch": "partial"},
            status="PARTIAL_FAIL",
            failure_info="Requested dispatch not fully reached.",
        )
        db.session.add(execution)
        db.session.flush()

        outcome = OperationalOutcome(
            execution_id=execution.id,
            expected_outcome=json.dumps({"balance": True, "reserve": True}),
            actual_outcome=json.dumps({
                "snapshot_id": post_snapshot.id,
                "goal_result": "NOT_ACHIEVED",
                "replan_required": True,
                "goal_criteria": {"balance": False, "reserve": True},
            }),
            is_success=False,
            causes="Partial dispatch",
            operational_impact="Residual imbalance remained.",
            planning_implications="Use current post-execution state.",
        )
        db.session.add(outcome)
        db.session.commit()
        return original.id, original_snapshot.id, post_snapshot.id


def _fake_generation(self, *, snapshot_id, horizon_minutes, risk_event_id=None,
                     reserve_assessment_id=None, objectives=None,
                     decision_policy_version="v1.0-demo",
                     required_candidate_count=4, strategies=None,
                     dynamic_pricing_tool_call_id=None):
    plans = []
    for index in range(required_candidate_count):
        plan = Plan(
            snapshot_id=snapshot_id,
            plan_name=f"Replacement {index + 1}",
            horizon_hours=2,
            actions={},
            status="PROPOSED",
            strategy_label=["SOLAR_ONLY", "BATTERY_ONLY", "MIXED", "COST_MIN"][index],
            imbalance_event_id=risk_event_id,
            assumptions="Generated by existing Tool 05 pipeline.",
        )
        db.session.add(plan)
        db.session.flush()
        plans.append(plan)
    db.session.commit()
    return {
        "generated": {"plans": [{"plan_id": p.id} for p in plans]},
        "evaluated": {"selected_plan_id": plans[0].id},
        "selected_plan_id": plans[0].id,
    }


def test_post_execution_not_achieved_generates_replacement_with_current_state_and_parent(
    app, recovery_case, monkeypatch
):
    monkeypatch.setattr(PlannerAgent, "build_and_validate_plans", _fake_generation)

    with app.app_context():
        original_id, _, current_snapshot_id = recovery_case
        planner = PlannerAgent(context=type("Ctx", (), {"db": db, "session": db.session, "run_id": 99})())

        result = planner.replan_after_execution(plan_id=original_id, required_candidate_count=2)

        assert result["status"] == "REPLAN_GENERATED"
        assert result["current_snapshot_id"] == current_snapshot_id
        assert len(result["plans"]) == 2

        children = Plan.query.filter_by(parent_plan_id=original_id).order_by(Plan.id).all()
        assert len(children) == 2
        assert all(child.snapshot_id == current_snapshot_id for child in children)
        assert all(child.status == "PROPOSED" for child in children)
        assert all(child.approval is None for child in children)
        assert all(child.execution is None for child in children)
        assert all("source_execution_id=" in (child.assumptions or "") for child in children)


def test_duplicate_replan_reuses_active_replacement_without_generating_again(
    app, recovery_case, monkeypatch
):
    calls = {"count": 0}

    def generation(*args, **kwargs):
        calls["count"] += 1
        return _fake_generation(*args, **kwargs)

    monkeypatch.setattr(PlannerAgent, "build_and_validate_plans", generation)

    with app.app_context():
        original_id, _, _ = recovery_case
        planner = PlannerAgent(context=type("Ctx", (), {"db": db, "session": db.session, "run_id": 100})())

        first = planner.replan_after_execution(plan_id=original_id, required_candidate_count=1)
        second = planner.replan_after_execution(plan_id=original_id, required_candidate_count=1)

        assert first["status"] == "REPLAN_GENERATED"
        assert second["status"] == "REPLAN_ALREADY_EXISTS"
        assert calls["count"] == 1
        assert len(Plan.query.filter_by(parent_plan_id=original_id).all()) == 1


def test_successful_execution_cannot_trigger_recovery_replan(app, recovery_case, monkeypatch):
    monkeypatch.setattr(PlannerAgent, "build_and_validate_plans", _fake_generation)

    with app.app_context():
        original_id, _, _ = recovery_case
        execution = Plan.query.get(original_id).execution
        execution.status = "SUCCESS"
        execution.outcome.actual_outcome = json.dumps({
            "goal_result": "ACHIEVED",
            "replan_required": False,
        })
        db.session.commit()

        planner = PlannerAgent(context=type("Ctx", (), {"db": db, "session": db.session, "run_id": 101})())
        with pytest.raises(ValueError, match="does not require replanning"):
            planner.replan_after_execution(plan_id=original_id)


def test_replan_api_uses_dedicated_operation_and_never_auto_approves_or_executes(
    app, recovery_case, monkeypatch
):
    monkeypatch.setattr(PlannerAgent, "build_and_validate_plans", _fake_generation)

    client = app.test_client()
    original_id, _, _ = recovery_case

    response = client.post(f"/api/plans/{original_id}/replan", json={"required_candidate_count": 1})
    assert response.status_code == 200
    payload = response.get_json()["result"]
    assert payload["status"] == "REPLAN_GENERATED"
    assert payload["plans"][0]["parent_plan_id"] == original_id

    with app.app_context():
        child = Plan.query.filter_by(parent_plan_id=original_id).one()
        assert child.status == "PROPOSED"
        assert child.approval is None
        assert child.execution is None


def test_replan_api_rejects_plan_without_execution_or_outcome(app):
    with app.app_context():
        snapshot = SystemSnapshot(
            timestamp=datetime.utcnow(),
            demand_mw=50,
            solar_gen_mw=40,
            other_gen_mw=0,
            state_json={"batteries": []},
        )
        db.session.add(snapshot)
        db.session.flush()
        plan = Plan(
            snapshot_id=snapshot.id,
            plan_name="No execution",
            horizon_hours=2,
            actions={},
            status="PROPOSED",
        )
        db.session.add(plan)
        db.session.commit()
        plan_id = plan.id

    response = app.test_client().post(f"/api/plans/{plan_id}/replan", json={})
    assert response.status_code == 400
    assert "No execution/outcome exists" in response.get_json()["error"]["message"]


def test_ui_replan_action_is_state_gated_and_calls_dedicated_endpoint():
    js = open("static/js/main.js", encoding="utf-8").read()
    assert "if(!blocked&&replan)" in js
    assert "post(`/api/plans/${planId}/replan`" in js
    assert "Auto approval" in js
    assert "Parent Plan #" in js




def test_production_execution_uses_configured_budget_for_post_execution_replan(app, monkeypatch):
    """The execute API must not fall back to the generic 16-call interactive budget.

    The real recovery path can consume 21 deterministic tool calls in the worst case:
    Tool 12 + three Tool 16 topic lookups + Tool 13 + Tool 14 + Tool 02 (reserve refresh)
    + Tool 05 + twelve Tool 06-08 validations + Tool 09. The existing automation config
    deliberately provides 24 calls, so this test verifies that the API execution boundary
    actually uses that configured budget rather than silently constructing PlannerAgent()
    with its generic 16-call default.
    """
    captured = {}

    def fake_execute(self, *, plan_id, approval_id, current_snapshot_id):
        captured["max_tool_calls"] = self.limits.max_tool_calls
        captured["max_steps"] = self.limits.max_steps
        return {"status": "EXECUTION_ATTEMPTED", "execution": {"execution_id": 1}}

    monkeypatch.setattr(PlannerAgent, "execute_after_human_approval", fake_execute)

    # Use the real endpoint boundary, but replace the operation before any database
    # fixture is needed. The endpoint still constructs the production PlannerAgent.
    with app.app_context():
        from app import _run_with_trace
        result = _run_with_trace("PLAN_EXECUTION_BUDGET_REGRESSION", lambda planner: planner.execute_after_human_approval(
            plan_id=1, approval_id=1, current_snapshot_id=1
        ))

    assert result.status_code == 200
    assert captured["max_tool_calls"] == 24
    assert captured["max_steps"] == 32


def test_replan_budget_math_is_explicit_and_not_an_unbounded_increase():
    """Document the exact bounded recovery budget required by the current pipeline."""
    pre_replan = 1 + 3 + 1 + 1  # Tool 12 + Tool 16 topics + Tool 13 + Tool 14
    replan = 1 + (4 * 3) + 1 + 1  # Tool 02 if reserve refresh is needed + Tool 05 + 06-08 + Tool 09
    worst_case = pre_replan + replan

    assert worst_case == 21
    assert json.loads(open("config/automation_v1.json", encoding="utf-8").read())["planner_limits"]["max_tool_calls"] == 24
    assert 24 >= worst_case


def test_completed_tool14_recovery_automatically_invokes_existing_replan_operation(
    app, recovery_case, monkeypatch
):
    with app.app_context():
        original_id, _, _ = recovery_case
        planner = PlannerAgent(
            context=type("Ctx", (), {"db": db, "session": db.session, "run_id": 102})()
        )
        execution = Plan.query.get(original_id).execution
        calls = []

        def fake_call(name, payload):
            assert name == "assess_and_diagnose_outcome"
            return {
                "status": "SUCCESS",
                "data": {
                    "outcome_id": execution.outcome.id,
                    "goal_result": "NOT_ACHIEVED",
                    "replan_required": True,
                },
            }

        def fake_replan(*, plan_id, required_candidate_count=4, decision_policy_version="v1.0-demo"):
            calls.append((plan_id, required_candidate_count, decision_policy_version))
            return {
                "status": "REPLAN_GENERATED",
                "original_plan_id": plan_id,
                "current_snapshot_id": execution.outcome.id,
                "plans": [],
            }

        monkeypatch.setattr(planner, "_call", fake_call)
        monkeypatch.setattr(planner, "replan_after_execution", fake_replan)
        monkeypatch.setattr(
            "agents.planner_agent.SystemMemoryManager.evaluate_outcome_for_reusable_lesson",
            lambda self, outcome_id: {"status": "NOT_ELIGIBLE", "lesson_id": None},
        )

        result = planner.complete_post_execution_chain(execution_id=execution.id)

        assert result["status"] == "COMPLETED"
        assert result["replan"]["status"] == "REPLAN_GENERATED"
        assert calls == [(original_id, 4, "v1.0-demo")]


def test_recovery_view_offers_approve_only_for_proposed_feasible_candidates():
    js = (extract / "static/js/main.js").read_text(encoding="utf-8")
    assert "recovery-approve" in js
    assert "PROPOSED'&&feasible" in js
    assert "planAction(id,'approve')" in js
    assert "Not Executable" in js
    assert "automaticReplan" in js
